In [7]:
####1. display all the header tags from wikipedia.org
### URL:::: https://en.wikipedia.org/wiki/Main_Page
### URL:::: https://wikipedia.org

from urllib.request import urlopen
from bs4 import BeautifulSoup
wikiURL = input("Enter wiki URL: ")
html = urlopen(wikiURL)
bs = BeautifulSoup(html, "html.parser")
titles = bs.find_all(['h1', 'h2','h3','h4','h5','h6'])
print('\nList all the header tags :', *titles, sep='\n\n')

Enter wiki URL: https://en.wikipedia.org/wiki/Main_Page

List all the header tags :

<h1 class="firstHeading mw-first-heading" id="firstHeading" style="display: none"><span class="mw-page-title-main">Main Page</span></h1>

<h1><span class="mw-headline" id="Welcome_to_Wikipedia">Welcome to <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a></span></h1>

<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>

<h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>

<h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>

<h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>

<h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>

<h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>

<h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>

<h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>

<h2>Navigation menu</h2>

<h3 class="vector-menu-heading" id="p-personal-label">
<span class="vector-menu-heading-label">Personal tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-namespaces-label">
<span class="vector-menu-heading-label">Namespaces</span>
</h3>

<h3 class="vector-menu-heading" id="p-views-label">
<span class="vector-menu-heading-label">Views</span>
</h3>

<h3>
<label for="searchInput">Search</label>
</h3>

<h3 class="vector-menu-heading" id="p-navigation-label">
<span class="vector-menu-heading-label">Navigation</span>
</h3>

<h3 class="vector-menu-heading" id="p-interaction-label">
<span class="vector-menu-heading-label">Contribute</span>
</h3>

<h3 class="vector-menu-heading" id="p-tb-label">
<span class="vector-menu-heading-label">Tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-coll-print_export-label">
<span class="vector-menu-heading-label">Print/export</span>
</h3>

<h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
<span class="vector-menu-heading-label">In other projects</span>
</h3>

<h3 class="vector-menu-heading" id="p-lang-label">
<span class="vector-menu-heading-label">Languages</span>
</h3>

In [26]:
####2. IMDB’s Top rated 100 movies’ data


from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import re
html = urlopen('http://www.imdb.com/chart/top')
bs = BeautifulSoup(html, "html.parser")
movies = bs.select('td.titleColumn')
ratings = [b.attrs.get('data-value') for b in bs.select('td.posterColumn span[name=ir]')]


imdb = []

# Store each item into dictionary (data), then put those into a list (imdb)
for index in range(0, 100):
    # Seperate movie into: 'place', 'title', 'year'
    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    data = [movie_title,
            ratings[index],
            year
            ]
    imdb.append(data)
    
df = pd.DataFrame(imdb, columns=['Name', 'Rating', 'Year of Release'])

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
 
# All dataframes hereafter reflect these changes.
display(df)

,Name,Rating,Year of Release
0,The Shawshank Redemption,9.234735268038984,1994
1,The Godfather,9.156586870723254,1972
2,The Dark Knight,8.987543888158797,2008
3,The Godfather Part II,8.98454515479345,1974
4,12 Angry Men,8.949363785735875,1957
5,Schindler's List,8.936428010325393,1993
6,The Lord of the Rings: The Return of the King,8.923664871459929,2003
7,Pulp Fiction,8.849636088145573,1994
8,The Lord of the Rings: The Fellowship of the Ring,8.80501405535337,2001
9,"Il buono, il brutto, il cattivo",8.792594827492968,1966
10,Forrest Gump,8.767751481225735,1994
11,Fight Club,8.749241142367525,1999
12,Inception,8.733017816949562,2010
13,The Lord of the Rings: The Two Towers,8.729793906728249,2002
14,The Empire Strikes Back,8.701251003003161,1980
15,The Matrix,8.67060968177707,1999
16,Goodfellas,8.652668235027441,1990
17,One Flew Over the Cuckoo's Nest,8.640314230962993,1975
18,Se7en,8.604441021196145,1995
19,Shichinin no samurai,8.598913164726627,1954
20,It's a Wonderful Life,8.596834040234135,1946
21,The Silence of the Lambs,8.588352630319754,1991
22,Cidade de Deus,8.578959948348347,2002
23,Saving Private Ryan,8.578644245892583,1998
24,La vita è bella,8.566420452960317,1997
25,The Green Mile,8.560849750253173,1999
26,Interstellar,8.559826428648371,2014
27,Star Wars,8.552887549143048,1977
28,Terminator 2: Judgment Day,8.536644513901486,1991
29,Back to the Future,8.518368557740793,1985
30,Sen to Chihiro no kamikakushi,8.515313806799321,2001
31,Psycho,8.50823876630065,1960
32,The Pianist,8.505408054406052,2002
33,Léon,8.498601731964659,1994
34,Gisaengchung,8.49622894127339,2019
35,The Lion King,8.488445275907942,1994
36,Gladiator,8.486408320181326,2000
37,American History X,8.483837096538704,1998
38,The Departed,8.475661265975859,2006
39,The Usual Suspects,8.474650717953926,1995
40,The Prestige,8.468566896056668,2006
41,Casablanca,8.464243299318715,1942
42,Whiplash,8.462430643282556,2014
43,The Intouchables,8.453415068311525,2011
44,Hotaru no haka,8.45044574497426,1988
45,Seppuku,8.450345981882347,1962
46,Modern Times,8.448946474967633,1936
47,Once Upon a Time in the West,8.446524041807676,1968
48,Rear Window,8.43718806572839,1954
49,Alien,8.435194511047685,1979
50,City Lights,8.434126911837527,1931
51,Nuovo Cinema Paradiso,8.431085997255659,1988
52,Apocalypse Now,8.424884754545506,1979
53,Memento,8.424371292116739,2000
54,Raiders of the Lost Ark,8.410962688355388,1981
55,Django Unchained,8.404220085810975,2012
56,WALL·E,8.393358792224909,2008
57,The Lives of Others,8.385757023714177,2006
58,Sunset Blvd,8.382788652935696,1950
59,Top Gun: Maverick,8.378072500362716,2022
60,Paths of Glory,8.371671964826756,1957
61,The Shining,8.367060137598472,1980
62,The Great Dictator,8.365998438935385,1940
63,Witness for the Prosecution,8.359112091035284,1957
64,Avengers: Infinity War,8.358534052674862,2018
65,Aliens,8.344782966047738,1986
66,American Beauty,8.335842779086697,1999
67,Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb,8.332221869548176,1964
68,Spider-Man: Into the Spider-Verse,8.330760681691919,2018
69,The Dark Knight Rises,8.328096447040304,2012
70,Oldeuboi,8.32002624387482,2003
71,Joker,8.317735208929756,2019
72,Amadeus,8.316004986046538,1984
73,Braveheart,8.315548911230264,1995
74,Toy Story,8.315093045639374,1995
75,Coco,8.312964083056727,2017
76,Inglourious Basterds,8.312819510959978,2009
77,Das Boot,8.31256485036233,1981
78,Mononoke-hime,8.303504785578024,1997
79,Avengers: Endgame,8.301933207441172,2019
80,Once Upon a Time in America,8.297964137650423,1984
81,Good Will Hunting,8.28803059615389,1997
82,Kimi no na wa,8.27769328366828,2016
83,Requiem for a Dream,8.275535501588465,2000
84,Toy Story 3,8.275513060964052,2010
85,Singin' in the Rain,8.273399494066226,1952
86,3 Idiots,8.270551369732278,2009
87,Star Wars: Episode VI - Return of the Jedi,8.267050508143845,1983
88,Tengoku to jigoku,8.266126381937502,1963
89,2001: A Space Odyssey,8.264042342181606,1968
90,Eternal Sunshine of the Spotless Mind,8.26333075524409,2004
91,Reservoir Dogs,8.263095877844933,1992
92,Capharnaüm,8.259674099364025,2018
93,Lawrence of Arabia,8.256167122310256,1962
94,Citizen Kane,8.255957757433377,1941
95,Jagten,8.255834081246173,2012
96,M - Eine Stadt sucht einen Mörder,8.254166825267948,1931
97,North by Northwest,8.252126364846328,1959
98,Idi i smotri,8.247448795633964,1985
99,Vertigo,8.246666840624902,1958

In [29]:
####3. IMDB’s Top rated 100 Indian movies’ data


from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import re
html = urlopen('https://www.imdb.com/india/top-rated-indian-movies/')
bs = BeautifulSoup(html, "html.parser")
movies = bs.select('td.titleColumn')
ratings = [b.attrs.get('data-value') for b in bs.select('td.posterColumn span[name=ir]')]


imdb = []

# Store each item into dictionary (data), then put those into a list (imdb)
for index in range(0, 100):
    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    data = [movie_title,
            ratings[index],
            year
            ]
    imdb.append(data)
    
df = pd.DataFrame(imdb, columns=['Name', 'Rating', 'Year of Release'])

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
 
# All dataframes hereafter reflect these changes.
display(df)

[<td class="titleColumn">
      1.
      <a href="/title/tt9263550/" title="Madhavan (dir.), Madhavan, Simran">Rocketry: The Nambi Effect</a>
<span class="secondaryInfo">(2022)</span>
</td>, <td class="titleColumn">
      2.
      <a href="/title/tt0367495/" title="Sundar C. (dir.), Kamal Haasan, Madhavan">Anbe Sivam</a>
<span class="secondaryInfo">(2003)</span>
</td>, <td class="titleColumn">
      3.
      <a href="/title/tt0079221/" title="Hrishikesh Mukherjee (dir.), Amol Palekar, Bindiya Goswami">Golmaal</a>
<span class="secondaryInfo">(1979)</span>
</td>, <td class="titleColumn">
      4.
      <a href="/title/tt0093603/" title="Mani Ratnam (dir.), Kamal Haasan, Saranya Ponvannan">Nayakan</a>
<span class="secondaryInfo">(1987)</span>
</td>, <td class="titleColumn">
      5.
      <a href="/title/tt15097216/" title="T.J. Gnanavel (dir.), Suriya, Lijo Mol Jose">Jai Bhim</a>
<span class="secondaryInfo">(2021)</span>
</td>, <td class="titleColumn">
      6.
      <a href="/title/tt8176054/" title="Mari Selvaraj (dir.), Kathir, Anandhi">Pariyerum Perumal</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      7.
      <a href="/title/tt1187043/" title="Rajkumar Hirani (dir.), Aamir Khan, Madhavan">3 Idiots</a>
<span class="secondaryInfo">(2009)</span>
</td>, <td class="titleColumn">
      8.
      <a href="/title/tt0052572/" title="Satyajit Ray (dir.), Soumitra Chatterjee, Sharmila Tagore">Apur Sansar</a>
<span class="secondaryInfo">(1959)</span>
</td>, <td class="titleColumn">
      9.
      <a href="/title/tt0214915/" title="Fazil (dir.), Shobana, Mohanlal">Manichitrathazhu</a>
<span class="secondaryInfo">(1993)</span>
</td>, <td class="titleColumn">
      10.
      <a href="/title/tt7466810/" title="Kiranraj K (dir.), Rakshit Shetty, Charlie">777 Charlie</a>
<span class="secondaryInfo">(2022)</span>
</td>, <td class="titleColumn">
      11.
      <a href="/title/tt8413338/" title="Madhu C. Narayanan (dir.), Shane Nigam, Soubin Shahir">Kumbalangi Nights</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      12.
      <a href="/title/tt0400234/" title="Anurag Kashyap (dir.), Kay Kay Menon, Pawan Malhotra">Black Friday</a>
<span class="secondaryInfo">(2004)</span>
</td>, <td class="titleColumn">
      13.
      <a href="/title/tt10189514/" title="Sudha Kongara (dir.), Suriya, Paresh Rawal">Soorarai Pottru</a>
<span class="secondaryInfo">(2020)</span>
</td>, <td class="titleColumn">
      14.
      <a href="/title/tt7391996/" title="Venkatesh Maha (dir.), Radha Bessy, Subba Rao Vepada">C/o Kancharapalem</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      15.
      <a href="/title/tt10534500/" title="Rojin Thomas (dir.), Indrans, Sreenath Bhasi">#Home</a>
<span class="secondaryInfo">(2021)</span>
</td>, <td class="titleColumn">
      16.
      <a href="/title/tt0986264/" title="Aamir Khan (dir.), Darsheel Safary, Aamir Khan">Taare Zameen Par</a>
<span class="secondaryInfo">(2007)</span>
</td>, <td class="titleColumn">
      17.
      <a href="/title/tt0237376/" title="Sibi Malayil (dir.), Mohanlal, Thilakan">Kireedam</a>
<span class="secondaryInfo">(1989)</span>
</td>, <td class="titleColumn">
      18.
      <a href="/title/tt5074352/" title="Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar">Dangal</a>
<span class="secondaryInfo">(2016)</span>
</td>, <td class="titleColumn">
      19.
      <a href="/title/tt9900782/" title="Lokesh Kanagaraj (dir.), Karthi, Narain">Kaithi</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      20.
      <a href="/title/tt8948790/" title="Gowtam Tinnanuri (dir.), Nani, Shraddha Srinath">Jersey</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      21.
      <a href="/title/tt7019842/" title="C. Prem Kumar (dir.), Vijay Sethupathi, Adithya Bhaskar">96</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      22.
      <a href="/title/tt9477520/" title="Vetrimaaran (dir.), Dhanush, Manju Warrier">Asuran</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      23.
      <a href="/title/tt0105575/" title="Bharathan (dir.), Kamal Haasan, Shivaji Ganesan">Thevar Magan</a>
<span class="secondaryInfo">(1992)</span>
</td>, <td class="titleColumn">
      24.
      <a href="/title/tt4991384/" title="Vetrimaaran (dir.), Dinesh, Samuthirakani">Visaaranai</a>
<span class="secondaryInfo">(2015)</span>
</td>, <td class="titleColumn">
      25.
      <a href="/title/tt11580854/" title="Pa. Ranjith (dir.), Arya, Pasupathy">Sarpatta Parambarai</a>
<span class="secondaryInfo">(2021)</span>
</td>, <td class="titleColumn">
      26.
      <a href="/title/tt0101649/" title="Mani Ratnam (dir.), Rajinikanth, Mammootty">Thalapathi</a>
<span class="secondaryInfo">(1991)</span>
</td>, <td class="titleColumn">
      27.
      <a href="/title/tt0048473/" title="Satyajit Ray (dir.), Kanu Bannerjee, Karuna Bannerjee">Pather Panchali</a>
<span class="secondaryInfo">(1955)</span>
</td>, <td class="titleColumn">
      28.
      <a href="/title/tt5311546/" title="Mahesh Manjrekar (dir.), Nana Patekar, Medha Manjrekar">Natsamrat</a>
<span class="secondaryInfo">(2016)</span>
</td>, <td class="titleColumn">
      29.
      <a href="/title/tt12361178/" title="Jeethu Joseph (dir.), Mohanlal, Meena">Drishyam 2</a>
<span class="secondaryInfo">(2021)</span>
</td>, <td class="titleColumn">
      30.
      <a href="/title/tt0282778/" title="Sathyan Anthikad (dir.), Mohanlal, Sreenivasan">Nadodikkattu</a>
<span class="secondaryInfo">(1987)</span>
</td>, <td class="titleColumn">
      31.
      <a href="/title/tt4987556/" title="Mohan Raja (dir.), Jayam Ravi, Arvind Swamy">Thani Oruvan</a>
<span class="secondaryInfo">(2015)</span>
</td>, <td class="titleColumn">
      32.
      <a href="/title/tt10280296/" title="Shoojit Sircar (dir.), Vicky Kaushal, Shaun Scott">Sardar Udham</a>
<span class="secondaryInfo">(2021)</span>
</td>, <td class="titleColumn">
      33.
      <a href="/title/tt5959980/" title="Vetrimaaran (dir.), Dhanush, Ameer Sultan">Vada Chennai</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      34.
      <a href="/title/tt0048956/" title="Satyajit Ray (dir.), Pinaki Sengupta, Smaran Ghosal">Aparajito</a>
<span class="secondaryInfo">(1956)</span>
</td>, <td class="titleColumn">
      35.
      <a href="/title/tt0085743/" title="Kundan Shah (dir.), Naseeruddin Shah, Ravi Baswani">Jaane Bhi Do Yaaro</a>
<span class="secondaryInfo">(1983)</span>
</td>, <td class="titleColumn">
      36.
      <a href="/title/tt0466460/" title="Dibakar Banerjee (dir.), Anupam Kher, Boman Irani">Khosla Ka Ghosla!</a>
<span class="secondaryInfo">(2006)</span>
</td>, <td class="titleColumn">
      37.
      <a href="/title/tt3417422/" title="Jeethu Joseph (dir.), Mohanlal, Meena">Drishyam</a>
<span class="secondaryInfo">(2013)</span>
</td>, <td class="titleColumn">
      38.
      <a href="/title/tt0072783/" title="Hrishikesh Mukherjee (dir.), Dharmendra, Sharmila Tagore">Chupke Chupke</a>
<span class="secondaryInfo">(1975)</span>
</td>, <td class="titleColumn">
      39.
      <a href="/title/tt7738784/" title="Ram (dir.), Mammootty, Sadhana">Peranbu</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      40.
      <a href="/title/tt0376127/" title="S. Shankar (dir.), Vikram, Sada">Anniyan</a>
<span class="secondaryInfo">(2005)</span>
</td>, <td class="titleColumn">
      41.
      <a href="/title/tt10214826/" title="Swaroop Rsj (dir.), Naveen Polishetty, Shruti Sharma">Agent Sai Srinivasa Athreya</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      42.
      <a href="/title/tt7465992/" title="Nag Ashwin (dir.), Keerthy Suresh, Dulquer Salmaan">Mahanati</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      43.
      <a href="/title/tt7060344/" title="Ram Kumar (dir.), Vishnu Vishal, Amala Paul">Ratsasan</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      44.
      <a href="/title/tt3668162/" title="Anjali Menon (dir.), Dulquer Salmaan, Nivin Pauly">Bangalore Days</a>
<span class="secondaryInfo">(2014)</span>
</td>, <td class="titleColumn">
      45.
      <a href="/title/tt0195231/" title="Ram Gopal Varma (dir.), J.D. Chakravarthi, Manoj Bajpayee">Satya</a>
<span class="secondaryInfo">(1998)</span>
</td>, <td class="titleColumn">
      46.
      <a href="/title/tt9179430/" title="Lokesh Kanagaraj (dir.), Kamal Haasan, Vijay Sethupathi">Vikram</a>
<span class="secondaryInfo">(2022)</span>
</td>, <td class="titleColumn">
      47.
      <a href="/title/tt4679210/" title="Alphonse Puthren (dir.), Nivin Pauly, Sai Pallavi">Premam</a>
<span class="secondaryInfo">(2015)</span>
</td>, <td class="titleColumn">
      48.
      <a href="/title/tt7019942/" title="Thiagarajan Kumararaja (dir.), Vijay Sethupathi, Fahadh Faasil">Super Deluxe</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      49.
      <a href="/title/tt1954470/" title="Anurag Kashyap (dir.), Manoj Bajpayee, Richa Chadha">Gangs of Wasseypur</a>
<span class="secondaryInfo">(2012)</span>
</td>, <td class="titleColumn">
      50.
      <a href="/title/tt0291855/" title="I.V. Sasi (dir.), Mohanlal, Revathi">Devasuram</a>
<span class="secondaryInfo">(1993)</span>
</td>, <td class="titleColumn">
      51.
      <a href="/title/tt2356180/" title="Rakeysh Omprakash Mehra (dir.), Farhan Akhtar, Japtej Singh">Bhaag Milkha Bhaag</a>
<span class="secondaryInfo">(2013)</span>
</td>, <td class="titleColumn">
      52.
      <a href="/title/tt4430212/" title="Nishikant Kamat (dir.), Ajay Devgn, Shriya Saran">Drishyam</a>
<span class="secondaryInfo">(2015)</span>
</td>, <td class="titleColumn">
      53.
      <a href="/title/tt8108198/" title="Sriram Raghavan (dir.), Ayushmann Khurrana, Tabu">Andhadhun</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      54.
      <a href="/title/tt5867800/" title="Arun Prabhu Purushothaman (dir.), Aditi Balan, Padmashri Mohammad Ali">Aruvi</a>
<span class="secondaryInfo">(2016)</span>
</td>, <td class="titleColumn">
      55.
      <a href="/title/tt0312859/" title="Mani Ratnam (dir.), Keerthana Parthiepan, Simran">Kannathil Muthamittal</a>
<span class="secondaryInfo">(2002)</span>
</td>, <td class="titleColumn">
      56.
      <a href="/title/tt0214585/" title="Priyadarshan (dir.), Mohanlal, Nedumudi Venu">Chithram</a>
<span class="secondaryInfo">(1988)</span>
</td>, <td class="titleColumn">
      57.
      <a href="/title/tt6148156/" title="Gayatri (dir.), Madhavan, Vijay Sethupathi">Vikram Vedha</a>
<span class="secondaryInfo">(2017)</span>
</td>, <td class="titleColumn">
      58.
      <a href="/title/tt0059246/" title="Vijay Anand (dir.), Dev Anand, Waheeda Rehman">Guide</a>
<span class="secondaryInfo">(1965)</span>
</td>, <td class="titleColumn">
      59.
      <a href="/title/tt2181831/" title="Hansal Mehta (dir.), Rajkummar Rao, Prabhleen Sandhu">Shahid</a>
<span class="secondaryInfo">(2012)</span>
</td>, <td class="titleColumn">
      60.
      <a href="/title/tt1562872/" title="Zoya Akhtar (dir.), Hrithik Roshan, Farhan Akhtar">Zindagi Na Milegi Dobara</a>
<span class="secondaryInfo">(2011)</span>
</td>, <td class="titleColumn">
      61.
      <a href="/title/tt5312232/" title="Nagraj Manjule (dir.), Rinku Rajguru, Akash Thosar">Sairat</a>
<span class="secondaryInfo">(2016)</span>
</td>, <td class="titleColumn">
      62.
      <a href="/title/tt0119385/" title="Mani Ratnam (dir.), Mohanlal, Aishwarya Rai Bachchan">Iruvar</a>
<span class="secondaryInfo">(1997)</span>
</td>, <td class="titleColumn">
      63.
      <a href="/title/tt8239946/" title="Rahi Anil Barve (dir.), Sohum Shah, Jyoti Malshe">Tumbbad</a>
<span class="secondaryInfo">(2018)</span>
</td>, <td class="titleColumn">
      64.
      <a href="/title/tt1620933/" title="Tigmanshu Dhulia (dir.), Irrfan Khan, Mahie Gill">Paan Singh Tomar</a>
<span class="secondaryInfo">(2012)</span>
</td>, <td class="titleColumn">
      65.
      <a href="/title/tt9052870/" title="Nitesh Tiwari (dir.), Sushant Singh Rajput, Shraddha Kapoor">Chhichhore</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      66.
      <a href="/title/tt0220656/" title="S. Shankar (dir.), Arjun Sarja, Manisha Koirala">Mudhalvan</a>
<span class="secondaryInfo">(1999)</span>
</td>, <td class="titleColumn">
      67.
      <a href="/title/tt6380520/" title="Karthick Naren (dir.), Rahman, Prakash Raghavan">Dhuruvangal Pathinaaru</a>
<span class="secondaryInfo">(2016)</span>
</td>, <td class="titleColumn">
      68.
      <a href="/title/tt0292246/" title="Bhadran (dir.), Chippy, K.P.A.C. Lalitha">Spadikam</a>
<span class="secondaryInfo">(1995)</span>
</td>, <td class="titleColumn">
      69.
      <a href="/title/tt0367110/" title="Ashutosh Gowariker (dir.), Shah Rukh Khan, Gayatri Joshi">Swades: We, the People</a>
<span class="secondaryInfo">(2004)</span>
</td>, <td class="titleColumn">
      70.
      <a href="/title/tt0871510/" title="Shimit Amin (dir.), Shah Rukh Khan, Vidya Malvade">Chak De! India</a>
<span class="secondaryInfo">(2007)</span>
</td>, <td class="titleColumn">
      71.
      <a href="/title/tt0375611/" title="Sanjay Leela Bhansali (dir.), Amitabh Bachchan, Rani Mukerji">Black</a>
<span class="secondaryInfo">(2005)</span>
</td>, <td class="titleColumn">
      72.
      <a href="/title/tt0104561/" title="Mansoor Khan (dir.), Aamir Khan, Ayesha Jhulka">Jo Jeeta Wohi Sikandar</a>
<span class="secondaryInfo">(1992)</span>
</td>, <td class="titleColumn">
      73.
      <a href="/title/tt0459516/" title="K. Selvaraghavan (dir.), Dhanush, Sneha">Pudhu Pettai</a>
<span class="secondaryInfo">(2006)</span>
</td>, <td class="titleColumn">
      74.
      <a href="/title/tt8291224/" title="Aditya Dhar (dir.), Vicky Kaushal, Paresh Rawal">Uri: The Surgical Strike</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      75.
      <a href="/title/tt4429128/" title="Jeethu Joseph (dir.), Kamal Haasan, Gautami">Papanasam</a>
<span class="secondaryInfo">(2015)</span>
</td>, <td class="titleColumn">
      76.
      <a href="/title/tt10687070/" title="Madonne Ashwin (dir.), Yogi Babu, Sheela Rajkumar">Mandela</a>
<span class="secondaryInfo">(2021)</span>
</td>, <td class="titleColumn">
      77.
      <a href="/title/tt0050870/" title="Guru Dutt (dir.), Guru Dutt, Waheeda Rehman">Pyaasa</a>
<span class="secondaryInfo">(1957)</span>
</td>, <td class="titleColumn">
      78.
      <a href="/title/tt0374887/" title="Rajkumar Hirani (dir.), Sanjay Dutt, Arshad Warsi">Munna Bhai M.B.B.S.</a>
<span class="secondaryInfo">(2003)</span>
</td>, <td class="titleColumn">
      79.
      <a href="/title/tt10324144/" title="Anubhav Sinha (dir.), Ayushmann Khurrana, Nassar">Article 15</a>
<span class="secondaryInfo">(2019)</span>
</td>, <td class="titleColumn">
      80.
      <a href="/title/tt2877108/" title="Nalan Kumarasamy (dir.), Vijay Sethupathi, Sanchita Shetty">Soodhu Kavvum</a>
<span class="secondaryInfo">(2013)</span>
</td>, <td class="titleColumn">
      81.
      <a href="/title/tt3322420/" title="Vikas Bahl (dir.), Kangana Ranaut, Rajkummar Rao">Queen</a>
<span class="secondaryInfo">(2013)</span>
</td>, <td class="titleColumn">
      82.
      <a href="/title/tt4934950/" title="Meghna Gulzar (dir.), Irrfan Khan, Konkona Sen Sharma">Talvar</a>
<span class="secondaryInfo">(2015)</span>
</td>, <td class="titleColumn">
      83.
      <a href="/title/tt3973410/" title="M. Manikandan (dir.), Ramesh Thilaganathan, J. Vignesh">Kaakkaa Muttai</a>
<span class="secondaryInfo">(2014)</span>
</td>, <td class="titleColumn">
      84.
      <a href="/title/tt0169102/" title="Ashutosh Gowariker (dir.), Aamir Khan, Raghuvir Yadav">Lagaan: Once Upon a Time in India</a>
<span class="secondaryInfo">(2001)</span>
</td>, <td class="titleColumn">
      85.
      <a href="/title/tt2338151/" title="Rajkumar Hirani (dir.), Aamir Khan, Anushka Sharma">PK</a>
<span class="secondaryInfo">(2014)</span>
</td>, <td class="titleColumn">
      86.
      <a href="/title/tt2283748/" title="Umesh Shukla (dir.), Paresh Rawal, Akshay Kumar">OMG: Oh My God!</a>
<span class="secondaryInfo">(2012)</span>
</td>, <td class="titleColumn">
      87.
      <a href="/title/tt3569782/" title="Karthik Subbaraj (dir.), Siddharth, Bobby Simha">Jigarthanda</a>
<span class="secondaryInfo">(2014)</span>
</td>, <td class="titleColumn">
      88.
      <a href="/title/tt0200087/" title="John Mathew Matthan (dir.), Aamir Khan, Naseeruddin Shah">Sarfarosh</a>
<span class="secondaryInfo">(1999)</span>
</td>, <td class="titleColumn">
      89.
      <a href="/title/tt0242519/" title="Priyadarshan (dir.), Akshay Kumar, Suniel Shetty">Hera Pheri</a>
<span class="secondaryInfo">(2000)</span>
</td>, <td class="titleColumn">
      90.
      <a href="/title/tt1639426/" title="Vikramaditya Motwane (dir.), Rajat Barmecha, Ronit Roy">Udaan</a>
<span class="secondaryInfo">(2010)</span>
</td>, <td class="titleColumn">
      91.
      <a href="/title/tt2082197/" title="Anurag Basu (dir.), Ranbir Kapoor, Priyanka Chopra Jonas">Barfi!</a>
<span class="secondaryInfo">(2012)</span>
</td>, <td class="titleColumn">
      92.
      <a href="/title/tt7060460/" title="H. Vinoth (dir.), Karthi, Rakul Preet Singh">Theeran Adhigaaram Ondru</a>
<span class="secondaryInfo">(2017)</span>
</td>, <td class="titleColumn">
      93.
      <a href="/title/tt0073707/" title="Ramesh Sippy (dir.), Sanjeev Kumar, Dharmendra">Sholay</a>
<span class="secondaryInfo">(1975)</span>
</td>, <td class="titleColumn">
      94.
      <a href="/title/tt2218988/" title="Anwar Rasheed (dir.), Dulquer Salmaan, Thilakan">Ustad Hotel</a>
<span class="secondaryInfo">(2012)</span>
</td>, <td class="titleColumn">
      95.
      <a href="/title/tt0319736/" title="Rajkumar Santoshi (dir.), Ajay Devgn, Sushant Singh">The Legend of Bhagat Singh</a>
<span class="secondaryInfo">(2002)</span>
</td>, <td class="titleColumn">
      96.
      <a href="/title/tt0215517/" title="Gulzar (dir.), Sanjeev Kumar, Moushumi Chatterjee">Angoor</a>
<span class="secondaryInfo">(1982)</span>
</td>, <td class="titleColumn">
      97.
      <a href="/title/tt0405508/" title="Rakeysh Omprakash Mehra (dir.), Aamir Khan, Soha Ali Khan">Rang De Basanti</a>
<span class="secondaryInfo">(2006)</span>
</td>, <td class="titleColumn">
      98.
      <a href="/title/tt4849438/" title="S.S. Rajamouli (dir.), Prabhas, Rana Daggubati">Baahubali 2: The Conclusion</a>
<span class="secondaryInfo">(2017)</span>
</td>, <td class="titleColumn">
      99.
      <a href="/title/tt0139876/" title="Suresh Krishna (dir.), Rajinikanth, Nagma">Baasha</a>
<span class="secondaryInfo">(1995)</span>
</td>, <td class="titleColumn">
      100.
      <a href="/title/tt0364647/" title="Kamal Haasan (dir.), Kamal Haasan, Abhirami">Virumandi</a>
<span class="secondaryInfo">(2004)</span>
</td>, <td class="titleColumn">
      101.
      <a href="/title/tt4635372/" title="Neeraj Ghaywan (dir.), Richa Chadha, Sanjay Mishra">Masaan</a>
<span class="secondaryInfo">(2015)</span>
</td>, <td class="titleColumn">
      102.
      <a href="/title/tt1821480/" title="Sujoy Ghosh (dir.), Vidya Balan, Parambrata Chattopadhyay">Kahaani</a>
<span class="secondaryInfo">(2012)</span>
</td>, <td class="titleColumn">
      103.
      <a href="/title/tt4851630/" title="Dileesh Pothan (dir.), Fahadh Faasil, Aparna Balamurali">Maheshinte Prathikaaram</a>
<span class="secondaryInfo">(2016)</span>
</td>, <td class="titleColumn">
      104.
      <a href="/title/tt0292490/" title="Farhan Akhtar (dir.), Aamir Khan, Saif Ali Khan">Dil Chahta Hai</a>
<span class="secondaryInfo">(2001)</span>
</td>, <td class="titleColumn">
      105.

                                 Name             Rating Year of Release
0          Rocketry: The Nambi Effect  8.526198585508096            2022
1                          Anbe Sivam  8.397652817205648            2003
2                             Golmaal   8.38998421191544            1979
3                             Nayakan   8.38569768817641            1987
4                            Jai Bhim  8.380817596253788            2021
5                   Pariyerum Perumal  8.373950154058154            2018
6                            3 Idiots  8.350503810718681            2009
7                         Apur Sansar  8.346618074419137            1959
8                    Manichitrathazhu  8.327807256841643            1993
9                         777 Charlie   8.31394653690637            2022
10                  Kumbalangi Nights  8.313477340658572            2019
11                       Black Friday  8.312277900217639            2004
12                    Soorarai Pottru   8.30318224313121            2020
13                  C/o Kancharapalem  8.301218196738954            2018
14                              #Home  8.299371291388956            2021
15                   Taare Zameen Par  8.298747897417126            2007
16                           Kireedam  8.282542870737291            1989
17                             Dangal  8.281586193537136            2016
18                             Kaithi  8.278035865354145            2019
19                             Jersey  8.267442058727879            2019
20                                 96  8.243159426663576            2018
21                             Asuran  8.242770411469916            2019
22                       Thevar Magan  8.235675404689822            1992
23                         Visaaranai  8.231455910648162            2015
24                Sarpatta Parambarai  8.224921514773584            2021
25                         Thalapathi  8.222302485728846            1991
26                    Pather Panchali  8.221560204300932            1955
27                          Natsamrat  8.220514697885529            2016
28                         Drishyam 2  8.212573150652986            2021
29                       Nadodikkattu   8.19164004461675            1987
30                       Thani Oruvan  8.181363894686951            2015
31                       Sardar Udham  8.180360693646128            2021
32                       Vada Chennai  8.177253336599538            2018
33                          Aparajito  8.174015699731582            1956
34                 Jaane Bhi Do Yaaro  8.171772514633227            1983
35                  Khosla Ka Ghosla!  8.166205887624166            2006
36                           Drishyam  8.149085822300318            2013
37                      Chupke Chupke  8.138964392105207            1975
38                            Peranbu  8.136397153267513            2018
39                            Anniyan  8.136342621887737            2005
40        Agent Sai Srinivasa Athreya  8.134221995090282            2019
41                           Mahanati  8.133961701757144            2018
42                           Ratsasan  8.129087374720614            2018
43                     Bangalore Days  8.124595573363843            2014
44                              Satya  8.123881255796597            1998
45                             Vikram     8.121929092384            2022
46                             Premam  8.121803748856614            2015
47                       Super Deluxe  8.120961164215116            2019
48                 Gangs of Wasseypur  8.113131725478297            2012
49                          Devasuram  8.109206312507693            1993
50                 Bhaag Milkha Bhaag  8.106100719662896            2013
51                           Drishyam  8.103303420472743            2015
52                          Andhadhun  8.103234458133146            2018
53                              Aruvi  8.100799526684671            2016
54              Kannathil Muthamittal  8.095798070316153            2002
55                           Chithram  8.094312214258775            1988
56                       Vikram Vedha   8.09426631523618            2017
57                              Guide  8.093452985111947            1965
58                             Shahid     8.087807485209            2012
59           Zindagi Na Milegi Dobara  8.087193727916317            2011
60                             Sairat  8.087127744144366            2016
61                             Iruvar    8.0866542970585            1997
62                            Tumbbad  8.086638116655784            2018
63                   Paan Singh Tomar  8.084201922228203            2012
64                         Chhichhore  8.073669692710865            2019
65                          Mudhalvan   8.07213930921284            1999
66             Dhuruvangal Pathinaaru  8.065331379107011            2016
67                           Spadikam  8.065070206341764            1995
68             Swades: We, the People  8.064616904587075            2004
69                     Chak De! India  8.063993003216469            2007
70                              Black   8.06263637384623            2005
71             Jo Jeeta Wohi Sikandar  8.060103714250383            1992
72                       Pudhu Pettai  8.059806175494932            2006
73           Uri: The Surgical Strike  8.055720896570511            2019
74                          Papanasam  8.055403712063338            2015
75                            Mandela   8.05532018928577            2021
76                             Pyaasa  8.054792235645317            1957
77                    Munna Bhai MBBS  8.054615763492295            2003
78                         Article 15  8.050197564262948            2019
79                      Soodhu Kavvum  8.047783780279682            2013
80                              Queen  8.047645970106007            2013
81                             Talvar  8.045303317194584            2015
82                     Kaakkaa Muttai  8.045138064699646            2014
83  Lagaan: Once Upon a Time in India  8.044070028735518            2001
84                                 PK  8.042574695012208            2014
85                    OMG: Oh My God!  8.039311667071521            2012
86                        Jigarthanda  8.037119693426908            2014
87                          Sarfarosh  8.033368265124242            1999
88                         Hera Pheri  8.031712803842114            2000
89                              Udaan   8.03034554323339            2010
90                             Barfi!  8.030112904878058            2012
91           Theeran Adhigaaram Ondru  8.029705245188048            2017
92                             Sholay  8.028494301561004            1975
93                        Ustad Hotel  8.025424186007768            2012
94         The Legend of Bhagat Singh  8.020663191167099            2002
95                             Angoor  8.013610175412065            1982
96                    Rang De Basanti  8.013334027329728            2006
97        Baahubali 2: The Conclusion  8.012604977163013            2017
98                             Baasha  8.010502905502529            1995
99                          Virumandi  8.007555141048197            2004

In [40]:
####4. List of respected former presidents of India

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://presidentofindia.nic.in/former-presidents.htm')
bs = BeautifulSoup(html, "html.parser")
presidents = bs.find_all("div", {"class": "presidentListing"})

presidentsList = []

for index in range(0, len(presidents)):
    presidents_string = presidents[index].get_text()
    president = presidents_string.split('\n')[1]
    term = presidents_string.split('\n')[2].split(": ")[1]
    data = [president, term]
    presidentsList.append(data)

df = pd.DataFrame(presidentsList, columns=["Name","Term of Office"])
display(df)

,Name,Term of Office
0,Shri Ram Nath Kovind (birth - 1945),"25 July, 2017 to 25 July, 2022"
1,Shri Pranab Mukherjee (1935-2020),"25 July, 2012 to 25 July, 2017"
2,Smt Pratibha Devisingh Patil (birth - 1934),"25 July, 2007 to 25 July, 2012"
3,DR. A.P.J. Abdul Kalam (1931-2015),"25 July, 2002 to 25 July, 2007"
4,Shri K. R. Narayanan (1920 - 2005),"25 July, 1997 to 25 July, 2002"
5,Dr Shankar Dayal Sharma (1918-1999),"25 July, 1992 to 25 July, 1997"
6,Shri R Venkataraman (1910-2009),"25 July, 1987 to 25 July, 1992"
7,Giani Zail Singh (1916-1994),"25 July, 1982 to 25 July, 1987"
8,Shri Neelam Sanjiva Reddy (1913-1996),"25 July, 1977 to 25 July, 1982"
9,Dr. Fakhruddin Ali Ahmed (1905-1977),"24 August, 1974 to 11 February, 1977"
10,Shri Varahagiri Venkata Giri (1894-1980),"3 May, 1969 to 20 July, 1969 and 24 August, 1969 to 24 August, 1974"
11,Dr. Zakir Husain (1897-1969),"13 May, 1967 to 3 May, 1969"
12,Dr. Sarvepalli Radhakrishnan (1888-1975),"13 May, 1962 to 13 May, 1967"
13,Dr. Rajendra Prasad (1884-1963),"26 January, 1950 to 13 May, 1962"

In [12]:
####5. a) Top 10 ODI Teams

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
bs = BeautifulSoup(html, "html.parser")
firstTeamName = bs.select("td.rankings-block__banner--team-name span.u-hide-phablet")[0];
firstTeamMatches = bs.select("td.rankings-block__banner--matches")[0];
firstTeamPoints = bs.select("td.rankings-block__banner--points")[0];
firstTeamRating = bs.select("td.rankings-block__banner--rating")[0];
firstTeam = [firstTeamName.get_text(), firstTeamMatches.get_text(), firstTeamPoints.get_text(), firstTeamRating.get_text().strip()];


restTeams = bs.select("tr.table-body");
restTeamNames = bs.select("td.rankings-table__team span.u-hide-phablet");
restTeamMatchesPoints = bs.select("td.u-center-text");
restTeamRatings = bs.select("td.rating");

restTeamMatches = [];
restTeamPoints = [];

for index in range(0, len(restTeamMatchesPoints)):
    if (index%2 == 0):
        restTeamMatches.append(restTeamMatchesPoints[index].get_text());
    else:
        restTeamPoints.append(restTeamMatchesPoints[index].get_text());
        

teamList = []
teamList.append(firstTeam);

for index in range(0, 9):
    name = restTeamNames[index].get_text();
    matches = restTeamMatches[index];
    points = restTeamPoints[index];
    ratings = restTeamRatings[index].get_text();
    restTeam = [name, matches, points, ratings];
    teamList.append(restTeam);


df = pd.DataFrame(teamList, columns=["Name","Matches", "Points", "Rating"])
display(df)

           Name Matches Points Rating
0   New Zealand      19  2,355    124
1       England      27  3,226    119
2         India      31  3,447    111
3      Pakistan      22  2,354    107
4     Australia      25  2,548    102
5  South Africa      21  2,111    101
6    Bangladesh      30  2,753     92
7     Sri Lanka      29  2,658     92
8   West Indies      41  2,902     71
9   Afghanistan      18  1,238     69

In [13]:
####5. b) Top 10 ODI Batsmen

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')
bs = BeautifulSoup(html, "html.parser")
firstPlayerName = bs.select("div.rankings-block__banner--name-large")[0];
firstPlayerTeam = bs.select("div.rankings-block__banner--nationality")[0];
firstPlayerRating = bs.select("div.rankings-block__banner--rating")[0];

firstPlayer = [firstPlayerName.get_text().strip(),firstPlayerTeam.get_text().strip(),firstPlayerRating.get_text().strip()]

restPlayerName = bs.select("td.rankings-table__name");
restPlayerTeam = bs.select("td.rankings-table__team");
restPlayerRating = bs.select("td.rating");

playerList = []
playerList.append(firstPlayer);


for index in range(0,9):
    name = restPlayerName[index].get_text().strip();
    team = restPlayerTeam[index].get_text().strip();
    rating = restPlayerRating[index].get_text().strip();
    playerList.append([name,team,rating]);
    
df = pd.DataFrame(playerList, columns=["Name","Team", "Rating"])
display(df)

890

                    Name Team Rating
0             Babar Azam  PAK    890
1  Rassie van der Dussen   SA    789
2        Quinton de Kock   SA    784
3            Imam-ul-Haq  PAK    779
4            Virat Kohli  IND    744
5           Rohit Sharma  IND    740
6           David Warner  AUS    739
7         Jonny Bairstow  ENG    732
8            Ross Taylor   NZ    722
9            Aaron Finch  AUS    706

In [14]:
####5. c) Top 10 ODI Bowlers

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling')
bs = BeautifulSoup(html, "html.parser")
firstPlayerName = bs.select("div.rankings-block__banner--name-large")[0];
firstPlayerTeam = bs.select("div.rankings-block__banner--nationality")[0];
firstPlayerRating = bs.select("div.rankings-block__banner--rating")[0];

firstPlayer = [firstPlayerName.get_text().strip(),firstPlayerTeam.get_text().strip(),firstPlayerRating.get_text().strip()]

restPlayerName = bs.select("td.rankings-table__name");
restPlayerTeam = bs.select("td.rankings-table__team");
restPlayerRating = bs.select("td.rating");

playerList = []
playerList.append(firstPlayer);


for index in range(0,9):
    name = restPlayerName[index].get_text().strip();
    team = restPlayerTeam[index].get_text().strip();
    rating = restPlayerRating[index].get_text().strip();
    playerList.append([name,team,rating]);
    
df = pd.DataFrame(playerList, columns=["Name","Team", "Rating"])
display(df)

720

                Name Team Rating
0        Trent Boult   NZ    720
1     Josh Hazlewood  AUS    678
2   Mujeeb Ur Rahman  AFG    676
3     Jasprit Bumrah  IND    662
4     Shaheen Afridi  PAK    661
5      Mohammad Nabi  AFG    657
6       Mehedi Hasan  BAN    655
7        Rashid Khan  AFG    651
8         Matt Henry   NZ    644
9  Mustafizur Rahman  BAN    640

In [15]:
####6. a) Top 10 ODI Teams - Women

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')
bs = BeautifulSoup(html, "html.parser")
firstTeamName = bs.select("td.rankings-block__banner--team-name span.u-hide-phablet")[0];
firstTeamMatches = bs.select("td.rankings-block__banner--matches")[0];
firstTeamPoints = bs.select("td.rankings-block__banner--points")[0];
firstTeamRating = bs.select("td.rankings-block__banner--rating")[0];
firstTeam = [firstTeamName.get_text(), firstTeamMatches.get_text(), firstTeamPoints.get_text(), firstTeamRating.get_text().strip()];


restTeams = bs.select("tr.table-body");
restTeamNames = bs.select("td.rankings-table__team span.u-hide-phablet");
restTeamMatchesPoints = bs.select("td.u-center-text");
restTeamRatings = bs.select("td.rating");

restTeamMatches = [];
restTeamPoints = [];

for index in range(0, len(restTeamMatchesPoints)):
    if (index%2 == 0):
        restTeamMatches.append(restTeamMatchesPoints[index].get_text());
    else:
        restTeamPoints.append(restTeamMatchesPoints[index].get_text());
        

teamList = []
teamList.append(firstTeam);

for index in range(0, 9):
    name = restTeamNames[index].get_text();
    matches = restTeamMatches[index];
    points = restTeamPoints[index];
    ratings = restTeamRatings[index].get_text();
    restTeam = [name, matches, points, ratings];
    teamList.append(restTeam);


df = pd.DataFrame(teamList, columns=["Name","Matches", "Points", "Rating"])
display(df)

           Name Matches Points Rating
0     Australia      29  4,837    167
1       England      33  4,046    123
2  South Africa      35  4,157    119
3         India      32  3,219    101
4   New Zealand      31  3,019     97
5   West Indies      30  2,768     92
6    Bangladesh      12    930     78
7      Pakistan      30  1,962     65
8       Ireland      11    516     47
9     Sri Lanka      11    495     45

In [16]:
####6. b) Top 10 ODI Batsmen - Women

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')
bs = BeautifulSoup(html, "html.parser")
firstPlayerName = bs.select("div.rankings-block__banner--name-large")[0];
firstPlayerTeam = bs.select("div.rankings-block__banner--nationality")[0];
firstPlayerRating = bs.select("div.rankings-block__banner--rating")[0];

firstPlayer = [firstPlayerName.get_text().strip(),firstPlayerTeam.get_text().strip(),firstPlayerRating.get_text().strip()]

restPlayerName = bs.select("td.rankings-table__name");
restPlayerTeam = bs.select("td.rankings-table__team");
restPlayerRating = bs.select("td.rating");

playerList = []
playerList.append(firstPlayer);


for index in range(0,9):
    name = restPlayerName[index].get_text().strip();
    team = restPlayerTeam[index].get_text().strip();
    rating = restPlayerRating[index].get_text().strip();
    playerList.append([name,team,rating]);
    
df = pd.DataFrame(playerList, columns=["Name","Team", "Rating"])
display(df)

                  Name Team Rating
0         Alyssa Healy  AUS    785
1          Beth Mooney  AUS    749
2       Natalie Sciver  ENG    747
3      Laura Wolvaardt   SA    732
4          Meg Lanning  AUS    710
5       Rachael Haynes  AUS    701
6    Amy Satterthwaite   NZ    681
7       Tammy Beaumont  ENG    667
8  Chamari Athapaththu   SL    655
9      Smriti Mandhana  IND    649

In [17]:
####6. c) Top 10 ODI Bowlers - Women

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/bowling')
bs = BeautifulSoup(html, "html.parser")
firstPlayerName = bs.select("div.rankings-block__banner--name-large")[0];
firstPlayerTeam = bs.select("div.rankings-block__banner--nationality")[0];
firstPlayerRating = bs.select("div.rankings-block__banner--rating")[0];

firstPlayer = [firstPlayerName.get_text().strip(),firstPlayerTeam.get_text().strip(),firstPlayerRating.get_text().strip()]

restPlayerName = bs.select("td.rankings-table__name");
restPlayerTeam = bs.select("td.rankings-table__team");
restPlayerRating = bs.select("td.rating");

playerList = []
playerList.append(firstPlayer);


for index in range(0,9):
    name = restPlayerName[index].get_text().strip();
    team = restPlayerTeam[index].get_text().strip();
    rating = restPlayerRating[index].get_text().strip();
    playerList.append([name,team,rating]);
    
df = pd.DataFrame(playerList, columns=["Name","Team", "Rating"])
display(df)

                  Name Team Rating
0    Sophie Ecclestone  ENG    761
1        Jess Jonassen  AUS    725
2         Megan Schutt  AUS    722
3       Shabnim Ismail   SA    722
4       Jhulan Goswami  IND    644
5       Ayabonga Khaka   SA    634
6  Rajeshwari Gayakwad  IND    613
7      Hayley Matthews   WI    612
8      Katherine Brunt  ENG    601
9       Marizanne Kapp   SA    598

In [20]:
####7. News details from https://www.cnbc.com/world/?region=world

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.cnbc.com/world/?region=world')
bs = BeautifulSoup(html, "html.parser")
headLinesTimestampList = bs.select("time.LatestNews-timestamp");
headLinesTitleList = bs.select("a.LatestNews-headline");
headLinesLinkList = [b.attrs.get('href') for b in bs.select('a.LatestNews-headline')]


latest_news = []

for index in range(0,len(headLinesTitleList)):
    headline = headLinesTitleList[index].get_text();
    time = headLinesTimestampList[index].get_text();
    news_link = headLinesLinkList[index];
    latest_news.append([headline, time, news_link]);
    
df = pd.DataFrame(latest_news, columns=["Headline","Time", "News Link"])
display(df)

,Headline,Time,News Link
0,These are the Street’s favorite defensive stoc...,16 Min Ago,https://www.cnbc.com/2022/09/04/this-is-the-st...
1,"This $310,000 electric RV has heated floors an...",26 Min Ago,https://www.cnbc.com/2022/09/04/bowlus-all-ele...
2,Mark Zuckerberg: Social media is for 'building...,26 Min Ago,https://www.cnbc.com/2022/09/04/zuckerberg-soc...
3,How electric vehicle manufacturing could shrin...,1 Hour Ago,https://www.cnbc.com/2022/09/04/ev-manufacturi...
4,Here's how student loan forgiveness could impa...,1 Hour Ago,https://www.cnbc.com/2022/09/04/how-student-lo...
5,"Airlines revamp in-flight menus, from vegan me...",2 Hours Ago,https://www.cnbc.com/2022/09/04/airlines-revam...
6,Over 25 million watched 'The Lord of the Rings...,16 Hours Ago,https://www.cnbc.com/2022/09/03/amazon-says-th...
7,New study: These are the top 10 best cities in...,21 Hours Ago,https://www.cnbc.com/2022/09/03/top-10-best-ci...
8,You can still get at-home Covid tests for free...,21 Hours Ago,https://www.cnbc.com/2022/09/03/how-you-can-st...
9,France says imposing a price cap on Russian oi...,22 Hours Ago,https://www.cnbc.com/2022/09/03/france-says-im...
10,NASA delays Artemis moon mission after second ...,22 Hours Ago,https://www.cnbc.com/2022/09/03/nasa-delays-ar...
11,"How this 28-year old makes $189,000 a year off...",23 Hours Ago,https://www.cnbc.com/2022/09/03/how-this-28-ye...
12,Trump SPAC's survival at stake in Digital Worl...,23 Hours Ago,https://www.cnbc.com/2022/09/03/trump-spac-sha...
13,Analysts are raving about these top stocks the...,"September 3, 2022",https://www.cnbc.com/2022/09/03/buy-stocks-suc...
14,The housing tech revolution boosted by the pan...,"September 3, 2022",https://www.cnbc.com/2022/09/03/what-proptech-...
15,This couple had an Amazon-themed wedding to ce...,"September 3, 2022",https://www.cnbc.com/2022/09/03/amazon-themed-...
16,Here's how much the typical Gen Z worker makes...,"September 3, 2022",https://www.cnbc.com/2022/09/03/how-much-money...
17,"New omicron boosters are available, but it's u...","September 3, 2022",https://www.cnbc.com/2022/09/03/covid-19-omicr...
18,These charts show how the 2022 box office sizz...,"September 3, 2022",https://www.cnbc.com/2022/09/03/how-the-summer...
19,Inflation Reduction Act: Here's when you may c...,"September 3, 2022",https://www.cnbc.com/2022/09/03/inflation-redu...
20,Sen. Lindsey Graham says he was stating the ob...,"September 3, 2022",https://www.cnbc.com/2022/09/03/sen-graham-say...
21,EU economics chief says bloc is ready to react...,"September 3, 2022",https://www.cnbc.com/2022/09/03/europe-ready-t...
22,EU energy chief urges China and India to suppo...,"September 3, 2022",https://www.cnbc.com/2022/09/03/eu-urges-china...
23,Trump pick in key Michigan race threatened to ...,"September 2, 2022",https://www.cnbc.com/2022/09/02/trump-pick-in-...
24,How 'quiet quitting' became the next phase of ...,"September 2, 2022",https://www.cnbc.com/2022/09/02/how-quiet-quit...
25,Pro Picks: Watch all of Friday's big stock cal...,"September 2, 2022",https://www.cnbc.com/2022/09/02/pro-picks-watc...
26,Comcast executives expect Disney to stick to i...,"September 2, 2022",https://www.cnbc.com/2022/09/02/comcast-execut...
27,"Investing Club: The week in review, the week a...","September 2, 2022",https://www.cnbc.com/2022/09/02/investing-club...
28,What to watch in the markets in the week ahead,"September 2, 2022",https://www.cnbc.com/2022/09/02/as-wall-street...
29,John Podesta to join Biden's climate team as t...,"September 2, 2022",https://www.cnbc.com/2022/09/02/john-podesta-t...

In [21]:
####8. Most downloaded article https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles')
bs = BeautifulSoup(html, "html.parser")
PeperTitleList = bs.select("a.nrDZj");
AuthorList = bs.select("span.pgLAT");
PublishedDateList = bs.select("span.bKddwo");
PaperLinkList = [b.attrs.get('href') for b in bs.select('a.nrDZj')]


latest_papers = []

for index in range(0,len(PeperTitleList)):
    title = PeperTitleList[index].get_text().strip();
    author = AuthorList[index].get_text();
    publishedon = PublishedDateList[index].get_text();
    paper_link = PaperLinkList[index];
    latest_papers.append([title, author, publishedon, paper_link]);
    
df = pd.DataFrame(latest_papers, columns=["Paper Title","Authors", "Published Date", "Paper URL"])
display(df)

,Paper Title,Authors,Published Date,Paper URL
0,Reward is enough,"Silver, David, Singh, Satinder, Precup, Doina,...",October 2021,https://www.sciencedirect.com/science/article/...
1,Making sense of raw input,"Evans, Richard, Bošnjak, Matko and 5 more",October 2021,https://www.sciencedirect.com/science/article/...
2,Law and logic: A review from an argumentation ...,"Prakken, Henry, Sartor, Giovanni",October 2015,https://www.sciencedirect.com/science/article/...
3,Creativity and artificial intelligence,"Boden, Margaret A.",August 1998,https://www.sciencedirect.com/science/article/...
4,Artificial cognition for social human–robot in...,"Lemaignan, Séverin, Warnier, Mathieu and 3 more",June 2017,https://www.sciencedirect.com/science/article/...
5,Explanation in artificial intelligence: Insigh...,"Miller, Tim",February 2019,https://www.sciencedirect.com/science/article/...
6,Making sense of sensory input,"Evans, Richard, Hernández-Orallo, José and 3 more",April 2021,https://www.sciencedirect.com/science/article/...
7,Conflict-based search for optimal multi-agent ...,"Sharon, Guni, Stern, Roni, Felner, Ariel, Stur...",February 2015,https://www.sciencedirect.com/science/article/...
8,Between MDPs and semi-MDPs: A framework for te...,"Sutton, Richard S., Precup, Doina, Singh, Sati...",August 1999,https://www.sciencedirect.com/science/article/...
9,The Hanabi challenge: A new frontier for AI re...,"Bard, Nolan, Foerster, Jakob N. and 13 more",March 2020,https://www.sciencedirect.com/science/article/...
10,Evaluating XAI: A comparison of rule-based and...,"van der Waa, Jasper, Nieuwburg, Elisabeth, Cre...",February 2021,https://www.sciencedirect.com/science/article/...
11,Argumentation in artificial intelligence,"Bench-Capon, T.J.M., Dunne, Paul E.",October 2007,https://www.sciencedirect.com/science/article/...
12,Algorithms for computing strategies in two-pla...,"Bošanský, Branislav, Lisý, Viliam and 3 more",August 2016,https://www.sciencedirect.com/science/article/...
13,Multiple object tracking: A literature review,"Luo, Wenhan, Xing, Junliang and 4 more",April 2021,https://www.sciencedirect.com/science/article/...
14,Selection of relevant features and examples in...,"Blum, Avrim L., Langley, Pat",December 1997,https://www.sciencedirect.com/science/article/...
15,A survey of inverse reinforcement learning: Ch...,"Arora, Saurabh, Doshi, Prashant",August 2021,https://www.sciencedirect.com/science/article/...
16,Explaining individual predictions when feature...,"Aas, Kjersti, Jullum, Martin, Løland, Anders",September 2021,https://www.sciencedirect.com/science/article/...
17,A review of possible effects of cognitive bias...,"Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Joha...",June 2021,https://www.sciencedirect.com/science/article/...
18,Integrating social power into the decision-mak...,"Pereira, Gonçalo, Prada, Rui, Santos, Pedro A.",December 2016,https://www.sciencedirect.com/science/article/...
19,“That's (not) the output I expected!” On the r...,"Riveiro, Maria, Thill, Serge",September 2021,https://www.sciencedirect.com/science/article/...
20,Explaining black-box classifiers using post-ho...,"Kenny, Eoin M., Ford, Courtney, Quinn, Molly, ...",May 2021,https://www.sciencedirect.com/science/article/...
21,Algorithm runtime prediction: Methods & evalua...,"Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyto...",January 2014,https://www.sciencedirect.com/science/article/...
22,Wrappers for feature subset selection,"Kohavi, Ron, John, George H.",December 1997,https://www.sciencedirect.com/science/article/...
23,Commonsense visual sensemaking for autonomous ...,"Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srik...",October 2021,https://www.sciencedirect.com/science/article/...
24,"Quantum computation, quantum theory and AI","Ying, Mingsheng",February 2010,https://www.sciencedirect.com/science/article/...

In [25]:
####9. Details from dineout.co.in

from urllib.request import Request, urlopen
from bs4 import BeautifulSoup
import pandas as pd
hdr = {'User-Agent': 'Mozilla/5.0'}
req = Request('https://www.dineout.co.in/delhi-restaurants/buffet-special',headers=hdr)
html = urlopen(req)
bs = BeautifulSoup(html, "html.parser")
NameList = bs.select("a.restnt-name");
CuisineList = bs.select("span.double-line-ellipsis a");
Location = bs.select("div.restnt-loc");
Ratings = bs.select("div.restnt-rating");
ImgURL = [b.attrs.get('data-src') for b in bs.select('img.no-img')]




restaurant_list = []


for index in range(0,len(NameList)):
    name = NameList[index].get_text().strip();
    cuisine = CuisineList[index].get_text().strip();
    location = Location[index].get_text().strip();
    ratings = Ratings[index].get_text();
    imgURL = ImgURL[index];
    restaurant_list.append([name, cuisine, location, ratings, imgURL]);
    
df = pd.DataFrame(restaurant_list, columns=["Restaurant Name","Cuisine", "Location", "Ratings","Image URL"])
display(df)

,Restaurant Name,Cuisine,Location,Ratings,Image URL
0,Castle Barbeque,Chinese,"Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
1,Jungle Jamboree,North Indian,"3CS Mall,Lajpat Nagar - 3, South Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
2,Castle Barbeque,North Indian,"Pacific Mall,Tagore Garden, West Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
3,Cafe Knosh,Asian,"The Leela Ambience Convention Hotel,Shahdara, ...",4.3,https://im1.dineout.co.in/images/uploads/resta...
4,The Barbeque Company,Italian,"Gardens Galleria,Sector 38A, Noida",3.9,https://im1.dineout.co.in/images/uploads/resta...
5,India Grill,Chinese,"Hilton Garden Inn,Saket, South Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
6,Delhi Barbeque,North Indian,"Taurus Sarovar Portico,Mahipalpur, South Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que Village,Italian,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad",4.3,https://im1.dineout.co.in/images/uploads/resta...
8,Indian Grill Room,Continental,"Suncity Business Tower,Golf Course Road, Gurgaon",4,https://im1.dineout.co.in/images/uploads/resta...

In [27]:
####10. Details of top publications from Google Scholar from https://scholar.google.com/citations?view_op=top_venues&hl=en

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://scholar.google.com/citations?view_op=top_venues&hl=en')
bs = BeautifulSoup(html, "html.parser")
RankList = bs.select("td.gsc_mvt_p");
PublicationList = bs.select("td.gsc_mvt_t");
h5Index = bs.select("td.gsc_mvt_n");
h5Median = bs.select('td.gsc_mvt_n')


top_publications = []

for index in range(0,len(RankList)):
    rank = RankList[index].get_text().strip();
    publication = PublicationList[index].get_text();
    h5_index = h5Index[index].get_text().strip();
    h5_median = h5Median[index].get_text().strip();
    top_publications.append([rank, publication, h5_index, h5_median]);
    
df = pd.DataFrame(top_publications, columns=["Rank","Publication", "h5-Index", "h5-Median"])
display(df)

    Rank                                        Publication h5-Index h5-Median
0     1.                                             Nature      444       444
1     2.                The New England Journal of Medicine      667       667
2     3.                                            Science      432       432
3     4.  IEEE/CVF Conference on Computer Vision and Pat...      780       780
4     5.                                         The Lancet      401       401
..   ...                                                ...      ...       ...
95   96.                       Journal of Business Research      296       296
96   97.                                   Molecular Cancer      173       173
97   98.                                            Sensors      228       228
98   99.                              Nature Climate Change      173       173
99  100.                    IEEE Internet of Things Journal      217       217

[100 rows x 4 columns]